FROM heroku/cedar:14
COPY ./build/linux/herokuish /bin/herokuish
RUN /bin/herokuish buildpack install \
	&& ln -s /bin/herokuish /build \
	&& ln -s /bin/herokuish /start \
	&& ln -s /bin/herokuish /exec
RUN sed -i '/apt.postgresql.org/d' /etc/apt/sources.list
